#!/bin/bash
## Copyright (C) 2022 Vivek Pal <31vivekpal@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

# Run shastra hooks related commands.

Lsb_release() {
    local file=/etc/lsb-release

    if [ -z "$(grep "^DISTRIB_CODENAME=" $file)" ] ; then
        # add missing DISTRIB_CODENAME=
        echo "DISTRIB_CODENAME=rolling" >> $file
    fi
    sed -i $file \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=ShastraOS|' \
        -e 's|^DISTRIB_CODENAME=.*$|DISTRIB_CODENAME=rolling|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"ShastraOS Linux\"|'
}

Os_release() {
    local file=/usr/lib/os-release
    local shastrafile=/usr/lib/shastraos-release

    # Get URLs from the ShastraOS web site!
    local home=https://shastraos.co
    local doc=https://shastraos.com/guide
    local support=https://shastraos.com
    local bugs=https://github.com/ShastraOS/shastra-iso/issues

    sed -i $file \
        -e 's|^NAME=.*$|NAME=ShastraOS|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=ShastraOS|' \
        -e "s|^HOME_URL=.*$|HOME_URL='$home'|" \
        -e "s|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL='$doc'|" \
        -e "s|^SUPPORT_URL=.*$|SUPPORT_URL='$support'|" \
        -e "s|^BUG_REPORT_URL=.*$|BUG_REPORT_URL='$bugs'|" \
        -e "s|^LOGO=.*$|LOGO=shastraos|" \
        -e "s|^ID=.*$|ID=shastraos|" \
        -e "s|^ID_LIKE=.*$|ID_LIKE=arch|"

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi
    if [ -r $shastrafile ] ; then
        # fix BUILD_ID for ShastraOS
        local buildid="$(grep "^VERSION=" $shastrafile | awk '{print $1}' | cut -d '=' -f 2)"
        sed -i $file -e "s|^BUILD_ID=.*$|BUILD_ID=$buildid|"
    fi
}

Issues() {
    sed -i 's|Arch|ShastraOS|g' /etc/issue /usr/share/factory/etc/issue
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
    esac
}

Main "$@"
